### PR TITLE
Support Cassandra 3.0

### PR DESCRIPTION
**Pull request by losblancos113**
- Change cassandra java driver to version 3.0.5.
- Modify source code to work with cassandra driver 3.0.5

### CODE REVIEW

**Comment by popcornylu** [comment]
Hi losblancos113, Thanks for your pull request. However, why the changed are the whole files? It is not easy for me to release what chunk are changed. Could you help to fix it?

**Comment by losblancos113** [comment]
Hi @popcornylu 
I modified those files because they are not compatible with Java driver version 3.0.5. Some methods are removed so I have to fix it. You can see more detail in this upgrade guide from Datastax
[http://docs.datastax.com/en/developer/java-driver/3.0/upgrade_guide/](url)

I think you could release 2 version 2.x and 3.0.x parallely because I'm not sure this change will work with all Cassandra version 2.x

**Comment by popcornylu** [comment]
Ok got it. I will take a look at these changes and test if it works on 2.x. These would take some days to check. Sorry i have to complete my job first ;)

**Comment by losblancos113** [comment]
Just get your job done first. 💃

**Comment by popcornylu** [comment]
I found the reason why whole files are marked as changed is because the tailing \r\n per line. I have transform these file to unix format. Pull request is merged.

**Pull request merged**
